# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:4.4.8
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example

  backend:
    image: wistron-care-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - HOST=http://localhost:9526
    depends_on:
      - mongo

  frontend:
    image: wistron-care-dashboard
    build:
      context: ./vue-admin-template
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9526:9526
    environment:
      - VUE_APP_BASE_API=http://localhost:3000/api/v1
    depends_on:
      - backend

volumes:
  mongodb:
